import mongoose from "mongoose";
import { Category, Product } from "./models/productModel";


async function createSampleData() {
  try {
    // Connect to MongoDB
    await mongoose.connect("mongodb://localhost:27017/your-database-name", {});

    // Create sample categories if needed
    const categories = await Category.insertMany([
      { name: "Pizza" },
      { name: "Burger" },
      { name: "Pasta" },
      { name: "Salad" },
      { name: "Sandwich" },
      { name: "Soup" },
      { name: "Sushi" },
      { name: "Taco" },
      { name: "Steak" },
      { name: "Seafood" },
      { name: "Chicken" },
      { name: "Rice Dish" },
      { name: "Dessert" },
      { name: "Breakfast" },
      { name: "Snack" },
      { name: "Vegetarian" },
      { name: "Vegan" },
      { name: "Gluten-Free" },
      { name: "Dairy-Free" },
      { name: "Low-Carb" },
    ]);

    // Create sample products
    await Product.create([
      {
        name: "Vegetable Pizza",
        image: "vegetable-pizza.jpg",
        description: "Delicious pizza topped with assorted vegetables",
        price: 10.99,
        categories: [categories[0]._id],
        stockQuantity: 30,
        userIP: "192.168.0.20",
        ingredients: ["Pizza Dough", "Tomato Sauce", "Assorted Vegetables", "Mozzarella Cheese"],
        servingSize: "1 slice (150g)",
        calories: 280,
        cookingInstructions: "Spread sauce on dough, add vegetables and cheese, bake until crust is golden brown.",
        isNewProduct: true,
        discountPercentage: 15,
        originalPrice: 12.99,
        allergens: ["Dairy", "Gluten"],
        dietaryRestrictions: ["Vegetarian"],
      },
      {
        name: "Veggie Burger",
        image: "veggie-burger.jpg",
        description: "Satisfying burger made with a vegetable patty, lettuce, tomato, and avocado",
        price: 9.49,
        categories: [categories[1]._id],
        stockQuantity: 25,
        userIP: "192.168.0.21",
        ingredients: ["Vegetable Patty", "Lettuce", "Tomato", "Avocado", "Burger Bun"],
        servingSize: "1 burger (200g)",
        calories: 350,
        cookingInstructions: "Grill the vegetable patty, assemble with lettuce, tomato, and avocado in the bun.",
        isNewProduct: false,
        allergens: ["Gluten"],
        dietaryRestrictions: ["Vegetarian"],
      },
      {
        name: "Penne Arrabiata",
        image: "penne-arrabiata.jpg",
        description: "Spicy pasta dish with penne in a tomato-based sauce",
        price: 11.49,
        categories: [categories[2]._id],
        stockQuantity: 20,
        userIP: "192.168.0.22",
        ingredients: ["Penne Pasta", "Tomato Sauce", "Chili Flakes", "Garlic", "Olive Oil"],
        servingSize: "1 plate (300g)",
        calories: 400,
        cookingInstructions: "Cook pasta al dente, sauté garlic and chili flakes in olive oil, toss with pasta and tomato sauce.",
        isNewProduct: true,
        discountPercentage: 10,
        originalPrice: 12.99,
        allergens: ["Gluten"],
        dietaryRestrictions: ["Vegetarian"],
      },
      {
        name: "Greek Salad",
        image: "greek-salad.jpg",
        description: "Traditional Greek salad with tomatoes, cucumbers, olives, feta cheese, and olive oil",
        price: 8.99,
        categories: [categories[3]._id],
        stockQuantity: 35,
        userIP: "192.168.0.23",
        ingredients: ["Tomatoes", "Cucumbers", "Olives", "Feta Cheese", "Olive Oil"],
        servingSize: "1 salad (250g)",
        calories: 220,
        cookingInstructions: "Combine all ingredients in a bowl, drizzle with olive oil, and toss gently.",
        isNewProduct: false,
        allergens: ["Dairy"],
        dietaryRestrictions: ["Vegetarian"],
      },
      {
        name: "Caprese Sandwich",
        image: "caprese-sandwich.jpg",
        description: "Fresh sandwich with mozzarella cheese, tomatoes, basil, and balsamic glaze",
        price: 7.49,
        categories: [categories[4]._id],
        stockQuantity: 40,
        userIP: "192.168.0.24",
        ingredients: ["Mozzarella Cheese", "Tomatoes", "Basil", "Balsamic Glaze", "Bread"],
        servingSize: "1 sandwich (150g)",
        calories: 300,
        cookingInstructions: "Layer cheese, tomatoes, and basil between slices of bread, drizzle with balsamic glaze.",
        isNewProduct: true,
        discountPercentage: 10,
        originalPrice: 8.49,
        allergens: ["Dairy", "Gluten"],
        dietaryRestrictions: ["Vegetarian"],
      },
      {
        name: "Minestrone Soup",
        image: "minestrone-soup.jpg",
        description: "Hearty Italian soup with vegetables, beans, and pasta in a savory broth",
        price: 6.99,
        categories: [categories[5]._id],
        stockQuantity: 30,
        userIP: "192.168.0.25",
        ingredients: ["Assorted Vegetables", "Beans", "Pasta", "Vegetable Broth"],
        servingSize: "1 bowl (300g)",
        calories: 250,
        cookingInstructions: "Simmer vegetables, beans, and pasta in broth until tender, season to taste.",
        isNewProduct: false,
        allergens: ["Gluten"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Vegetable Tempura",
        image: "vegetable-tempura.jpg",
        description: "Light and crispy tempura-fried vegetables served with dipping sauce",
        price: 8.99,
        categories: [categories[6]._id],
        stockQuantity: 25,
        userIP: "192.168.0.26",
        ingredients: ["Assorted Vegetables", "Tempura Batter", "Dipping Sauce"],
        servingSize: "1 plate (200g)",
        calories: 300,
        cookingInstructions: "Coat vegetables in tempura batter, fry until golden brown, serve with dipping sauce.",
        isNewProduct: true,
        discountPercentage: 15,
        originalPrice: 10.49,
        allergens: ["Gluten"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Vegetable Burrito",
        image: "vegetable-burrito.jpg",
        description: "Filling burrito stuffed with assorted vegetables, rice, beans, and salsa",
        price: 9.99,
        categories: [categories[7]._id],
        stockQuantity: 30,
        userIP: "192.168.0.27",
        ingredients: ["Assorted Vegetables", "Rice", "Beans", "Salsa", "Flour Tortilla"],
        servingSize: "1 burrito (300g)",
        calories: 400,
        cookingInstructions: "Fill tortilla with vegetables, rice, beans, and salsa, wrap tightly, and heat.",
        isNewProduct: false,
        allergens: ["Gluten"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Mushroom Risotto",
        image: "mushroom-risotto.jpg",
        description: "Creamy Italian risotto with mushrooms, Parmesan cheese, and white wine",
        price: 12.99,
        categories: [categories[11]._id],
        stockQuantity: 20,
        userIP: "192.168.0.28",
        ingredients: ["Arborio Rice", "Mushrooms", "Parmesan Cheese", "White Wine"],
        servingSize: "1 plate (300g)",
        calories: 450,
        cookingInstructions: "Sauté mushrooms, cook rice with white wine and broth, stir in cheese until creamy.",
        isNewProduct: true,
        discountPercentage: 10,
        originalPrice: 14.49,
        allergens: ["Dairy"],
        dietaryRestrictions: ["Vegetarian"],
      },
      {
        name: "Falafel Wrap",
        image: "falafel-wrap.jpg",
        description: "Tasty wrap filled with crispy falafel balls, lettuce, tomato, and tahini sauce",
        price: 8.49,
        categories: [categories[4]._id],
        stockQuantity: 35,
        userIP: "192.168.0.29",
        ingredients: ["Falafel", "Lettuce", "Tomato", "Tahini Sauce", "Flatbread"],
        servingSize: "1 wrap (200g)",
        calories: 350,
        cookingInstructions: "Warm flatbread, fill with falafel, lettuce, tomato, and drizzle with tahini sauce.",
        isNewProduct: false,
        allergens: ["Gluten"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Vegetable Fried Rice",
        image: "vegetable-fried-rice.jpg",
        description: "Flavorful fried rice with assorted vegetables and soy sauce",
        price: 7.99,
        categories: [categories[11]._id],
        stockQuantity: 30,
        userIP: "192.168.0.30",
        ingredients: ["Rice", "Assorted Vegetables", "Soy Sauce", "Garlic", "Sesame Oil"],
        servingSize: "1 plate (300g)",
        calories: 320,
        cookingInstructions: "Cook rice, sauté vegetables with garlic and soy sauce, stir in cooked rice.",
        isNewProduct: true,
        discountPercentage: 10,
        originalPrice: 8.99,
        allergens: ["Soy"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Mango Sorbet",
        image: "mango-sorbet.jpg",
        description: "Refreshing sorbet made with ripe mangoes and a hint of lime",
        price: 4.99,
        categories: [categories[12]._id],
        stockQuantity: 40,
        userIP: "192.168.0.31",
        ingredients: ["Mangoes", "Lime Juice", "Sugar", "Water"],
        servingSize: "1 scoop (100g)",
        calories: 120,
        cookingInstructions: "Blend mangoes, lime juice, sugar, and water until smooth, freeze until set.",
        isNewProduct: false,
        allergens: ["None"],
        dietaryRestrictions: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
      },
      {
        name: "Vegetable Curry",
        image: "vegetable-curry.jpg",
        description: "Spicy curry made with assorted vegetables and aromatic spices",
        price: 10.49,
        categories: [categories[11]._id],
        stockQuantity: 25,
        userIP: "192.168.0.32",
        ingredients: ["Assorted Vegetables", "Curry Paste", "Coconut Milk", "Spices"],
        servingSize: "1 bowl (300g)",
        calories: 380,
        cookingInstructions: "Sauté vegetables, add curry paste and coconut milk, simmer until vegetables are tender.",
        isNewProduct: true,
        discountPercentage: 10,
        originalPrice: 11.99,
        allergens: ["None"],
        dietaryRestrictions: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
      },
      {
        name: "Spinach and Feta Stuffed Mushrooms",
        image: "stuffed-mushrooms.jpg",
        description: "Mushroom caps filled with spinach, feta cheese, and breadcrumbs",
        price: 8.99,
        categories: [categories[14]._id],
        stockQuantity: 30,
        userIP: "192.168.0.33",
        ingredients: ["Mushroom Caps", "Spinach", "Feta Cheese", "Breadcrumbs"],
        servingSize: "4 mushrooms (150g)",
        calories: 180,
        cookingInstructions: "Remove mushroom stems, fill caps with spinach, feta, and breadcrumbs, bake until golden brown.",
        isNewProduct: false,
        allergens: ["Dairy", "Gluten"],
        dietaryRestrictions: ["Vegetarian"],
      },
      {
        name: "Vegetable Pad Thai",
        image: "vegetable-pad-thai.jpg",
        description: "Thai stir-fried noodles with assorted vegetables, tofu, and peanuts",
        price: 9.99,
        categories: [categories[11]._id],
        stockQuantity: 25,
        userIP: "192.168.0.34",
        ingredients: ["Rice Noodles", "Assorted Vegetables", "Tofu", "Peanuts", "Pad Thai Sauce"],
        servingSize: "1 plate (300g)",
        calories: 400,
        cookingInstructions: "Stir-fry vegetables, tofu, and noodles with pad Thai sauce, garnish with peanuts.",
        isNewProduct: true,
        discountPercentage: 10,
        originalPrice: 11.49,
        allergens: ["Peanuts", "Soy"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Eggplant Parmesan",
        image: "eggplant-parmesan.jpg",
        description: "Baked eggplant slices topped with marinara sauce, mozzarella, and Parmesan cheese",
        price: 10.99,
        categories: [categories[13]._id],
        stockQuantity: 20,
        userIP: "192.168.0.35",
        ingredients: ["Eggplant", "Marinara Sauce", "Mozzarella Cheese", "Parmesan Cheese"],
        servingSize: "1 serving (200g)",
        calories: 320,
        cookingInstructions: "Bread and bake eggplant slices, layer with marinara and cheese, bake until cheese melts.",
        isNewProduct: false,
        allergens: ["Dairy", "Gluten"],
        dietaryRestrictions: ["Vegetarian"],
      },
      {
        name: "Hummus Platter",
        image: "hummus-platter.jpg",
        description: "Creamy hummus served with pita bread, cucumber, carrot sticks, and olives",
        price: 7.99,
        categories: [categories[14]._id],
        stockQuantity: 30,
        userIP: "192.168.0.36",
        ingredients: ["Hummus", "Pita Bread", "Cucumber", "Carrot Sticks", "Olives"],
        servingSize: "1 platter",
        calories: 280,
        cookingInstructions: "Arrange hummus and accompaniments on a platter, serve with pita bread.",
        isNewProduct: true,
        discountPercentage: 15,
        originalPrice: 9.49,
        allergens: ["Gluten"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Stir-Fried Tofu with Vegetables",
        image: "tofu-stir-fry.jpg",
        description: "Tofu and vegetables stir-fried in a savory sauce",
        price: 8.49,
        categories: [categories[6]._id],
        stockQuantity: 25,
        userIP: "192.168.0.37",
        ingredients: ["Tofu", "Assorted Vegetables", "Soy Sauce", "Ginger", "Garlic"],
        servingSize: "1 plate (250g)",
        calories: 280,
        cookingInstructions: "Stir-fry tofu and vegetables in sauce until heated through, garnish with ginger and garlic.",
        isNewProduct: false,
        allergens: ["Soy"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Vegetable Lo Mein",
        image: "vegetable-lo-mein.jpg",
        description: "Chinese-style noodles stir-fried with assorted vegetables and soy sauce",
        price: 9.99,
        categories: [categories[11]._id],
        stockQuantity: 30,
        userIP: "192.168.0.38",
        ingredients: ["Lo Mein Noodles", "Assorted Vegetables", "Soy Sauce", "Sesame Oil"],
        servingSize: "1 plate (300g)",
        calories: 350,
        cookingInstructions: "Cook noodles, stir-fry vegetables with soy sauce and sesame oil, toss with noodles.",
        isNewProduct: true,
        discountPercentage: 10,
        originalPrice: 11.49,
        allergens: ["Gluten", "Soy"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Tomato Basil Bruschetta",
        image: "bruschetta.jpg",
        description: "Toasted bread topped with fresh tomatoes, basil, garlic, and olive oil",
        price: 6.49,
        categories: [categories[13]._id],
        stockQuantity: 35,
        userIP: "192.168.0.39",
        ingredients: ["Bread", "Tomatoes", "Basil", "Garlic", "Olive Oil"],
        servingSize: "4 pieces",
        calories: 200,
        cookingInstructions: "Toast bread, top with chopped tomatoes, basil, garlic, and drizzle with olive oil.",
        isNewProduct: false,
        allergens: ["Gluten"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
      {
        name: "Vegetable Stir-Fry",
        image: "vegetable-stir-fry.jpg",
        description: "Assorted vegetables stir-fried in a savory sauce",
        price: 8.99,
        categories: [categories[6]._id],
        stockQuantity: 30,
        userIP: "192.168.0.40",
        ingredients: ["Assorted Vegetables", "Soy Sauce", "Garlic", "Ginger", "Sesame Oil"],
        servingSize: "1 plate (250g)",
        calories: 200,
        cookingInstructions: "Stir-fry vegetables in sauce until tender, garnish with garlic, ginger, and sesame oil.",
        isNewProduct: true,
        discountPercentage: 10,
        originalPrice: 9.99,
        allergens: ["Soy"],
        dietaryRestrictions: ["Vegetarian", "Vegan"],
      },
    ]);

    console.log("Sample data created successfully.");
  } catch (error) {
    console.error("Error creating sample data:", error);
  } finally {
    // Disconnect from MongoDB
    await mongoose.disconnect();
  }
}

// Call the function to create sample data
createSampleData();
